server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://192.168.136.101:3307/hotel?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    username: elastic
    password: 123456
    connection-timeout: 10s
    uris: http://192.168.136.101:9200
  rabbitmq:
    username: lei
    password: 123456
    virtual-host: /
    host: 192.168.136.101
    port: 5672
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
logging:
  level:
    cn.itcast: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo

